config/routes.rb
Rails.application.routes.draw do
  resources :items
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "items#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  validates :transaction_date, :description, :amount, :category, presence: true
  validates :amount, numericality: {greater_than_or_equal_to: 0}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    if params[:search_choice] == "last_week"
      params[:start_date] = firstDay
      params[:end_date] = lastDay
      if params[:filter_list] != ""
        @items = Item.where(transaction_date: (params[:start_date]..params[:end_date]), category: params[:filter_list])
      else
        @items = Item.where(transaction_date: (params[:start_date]..params[:end_date]))
      end
    elsif params[:search_choice] == "view_month"
      date = Date.parse(params[:month_list])
      
      while date.day != 1
        date = date.prev_day
      end
      
      params[:start_date] = date
      
      while date.next_day.month != date.next_month.month
        date = date.next_day
      end
      
      params[:end_date] = date
      if params[:filter_list] != ""
        @items = Item.where(transaction_date: (params[:start_date]..params[:end_date]), category: params[:filter_list]).order(transaction_date: :desc)
      else
        @items = Item.where(transaction_date: (params[:start_date]..params[:end_date])).order(transaction_date: :desc)
      end
    elsif params[:search_choice] == "date_range"
      if params[:filter_list] != ""
        @items = Item.where(transaction_date: (params[:start_date]..params[:end_date]), category: params[:filter_list]).order(transaction_date: :desc)
      else
        @items = Item.where(transaction_date: (params[:start_date]..params[:end_date])).order(transaction_date: :desc)
      end
    else
      if params[:filter_list] == nil || params[:filter_list] == ""
        @items = Item.all.order(transaction_date: :desc)
      else
        @items = Item.where(category: params[:filter_list]).order(transaction_date: :desc)
      end
    end
    @debitTotal = @items.where(debit:true).sum(:amount)
    @creditTotal = @items.where(debit:false).sum(:amount)
    @categories = Item.select(:category).distinct
    $months = pastMonths()
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @categories = Item.select(:category).distinct
    @subcategories = Item.select(:subcategory).distinct
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
    @categories = Item.select(:category).distinct
    @subcategories = Item.select(:subcategory).distinct
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to items_url, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { redirect_to new_item_path }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to items_url, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { redirect_to edit_item_path }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:description, :amount, :debit, :category, :subcategory, :transaction_date)
    end
    
    def firstDay
      today = Date.today
      day = today.cwday
      if day == 7
        day = 0
      end
      return today - day - 7
    end
    
    def lastDay
      today = Date.today
      day = today.cwday
      if day == 7
        day = 0
      end
      return today - day - 1
    end

    def pastMonths
      date = Date.today.prev_month
      months = {}
      until months.length == 12
        if date.month < 10
          month = "0" + date.month.to_s
        else
          month = date.month
        end
        months[date.year.to_s + "-" + month.to_s] = date
        date = date.prev_month
      end
      return months
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="transaction-grid grid-container">
    <div class="label">Transaction date</div>
    <div class="label">Description</div>
    <div class="label">Debit</div>
    <div class="label">Amount</div>
    <div class="label">Category</div>
    <div class="label">Subcategory</div>
    <div class="label"></div>
    <!--
    <div><%=  form.date_select :transaction_date, id: :item_transaction_date %></div>
    -->
    <div>
      <% if !item.transaction_date %>
        <% item.transaction_date = Date.today %>
      <% end %>
      <%= form.text_field :transaction_date, id: :item_transaction_date, value: item.transaction_date, class:"flatpickr flatpickr-input", readonly:"readonly" %>
    </div>
    
    <div class="divClick"><%= form.text_field :description, id: :item_description %></div>
    <div class="divClick"><%= form.check_box :debit, id: :item_debit %></div>
    <div><%= form.text_field :amount, id: :item_amount %></div>
    <div class="divClick">
      <%= form.text_field :category, id: :item_category, list: "category-list" %>
      <datalist id="category-list">
        <% @categories.each do |category| %>
          <option><%= category.category %></option>
        <% end %>
      </datalist>
    </div>
    <div class="divClick">
      <%= form.text_field :subcategory, id: :item_subcategory, list: "subcategory-list" %>
      <datalist id="subcategory-list">
        <% @subcategories.each do |subcategory| %>
          <option><%= subcategory.subcategory %></option>
        <% end %>
      </datalist>
    </div>
    <div></div>
    <%= form.submit class: "row-button actions" %>
    <%= link_to 'Back', items_path, class: "row-button" %>
    <% if @edit=='true' %>
      <%= link_to 'Delete', @item, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </div>
<% end %>

<script type="text/javascript">

</script>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>
<%= link_to 'Delete', @item, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<div class="transaction-grid grid-container">
  <div class="label">Transaction date</div>
  <div class="label">Description</div>
  <div class="label">Income</div>
  <div class="label">Expense</div>
  <div class="label">Category</div>
  <div class="label">Subcategory</div>
  <div class="label"></div>
  <% @items.each do |item| %>
    <div><%= item.transaction_date %></div>
    <div><%= item.description %></div>
    <div>
      <% if item.debit %>
        <%= number_to_currency(item.amount) %>
      <% end %>
    </div>
    <div>
      <% if !item.debit %>
        -<%= number_to_currency(item.amount) %>
      <% end %>
    </div>
    <div><%= item.category %></div>
    <div><%= item.subcategory %></div>
    <%= link_to 'Edit', edit_item_path(item), class: "grid-edit-button" %>
  <% end %>
  <% if params[:start_date] %>
    <%= link_to 'Return', items_path, class: "row-button" %>
  <% end %>
</div>

<div class="total-grid grid-container">
  <div class="label">Total Income</div>
  <div class="label">Total Expense</div>
  <div class="label">Net</div>
  <div><%= number_to_currency @debitTotal %></div>
  <div>-<%= number_to_currency @creditTotal %></div>
  <div><%= number_to_currency (@debitTotal - @creditTotal) %></div>
</div>

<br>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class="center">Bookkeeper</h1>

<div class="transaction-grid">
  <div class="label">Transaction date</div>
  <div class="label">Description</div>
  <div class="label">Income</div>
  <div class="label">Expense</div>
  <div class="label">Category</div>
  <div class="label">Subcategory</div>
  <div class="label"></div>
  <div><%= @item.transaction_date %></div>
  <div><%= @item.description %></div>
  <div>
    <% if @item.debit %>
      <%= number_to_currency(@item.amount) %>
    <% end %>
  </div>
  <div>
    <% if !@item.debit %>
      -<%= number_to_currency(@item.amount) %>
    <% end %>
  </div>
  <div><%= @item.category %></div>
  <div><%= @item.subcategory %></div>
  <div><%= link_to 'Show', @item %></div>
</div>

<br>
<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Destroy', @item, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', items_path %>

app/views/layouts/_header.html.erb
<nav class="navbar">
  <a href="/" id="logo">Bookkeeper</a>
  <button id="search-drop" class="material-icons right">search</button>
</nav>


<div id="search-bar">
  <%= form_tag("/items", method: "get") do %>
    <div class="grid-container search-grid">
      <%= select_tag :search_choice, options_for_select([ ["Search by", ""], ["date range", "date_range"], ["last week", "last_week"], ["view month", "view_month"] ], "Search by") %>
      <% if params[:start_date] %>
        <% start_date = params[:start_date] %>
        <% end_date = params[:end_date] %>
      <% else %>
        <% start_date = Date.today %>
        <% end_date = Date.today %>
      <% end %>
      <%= select_tag :filter_list, options_from_collection_for_select(@categories, "category", "category"), include_blank: "Filter by" %>
      <%= text_field_tag :start_date, nil, id: :start_date, value: start_date, class:"flatpickr flatpickr-input select_range", readonly:"readonly" %>
      <%= text_field_tag :end_date, nil, id: :end_date, value: end_date, class:"flatpickr flatpickr-input select_range", readonly:"readonly" %>
      <div id="select_week" class="hidden-item">
        <%= check_box_tag :last_week, id: :last_week %>
      </div>
      <%= check_box_tag :check_month, id: :check_month %>
      <%= select_tag :month_list, options_for_select($months, $months[0]), class: "hidden-item row" %>
      <%= submit_tag "Search", class:"row-button" %>
    </div>
  <% end %>
</div>

<%= link_to "+".html_safe, new_item_path, class: "sidebar" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookkeeper</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="main">
      <%= yield %>
    </div>
  </body>
  <script>
    flatpickr('.flatpickr-input');
  </script>
</html>